spring:
  config:
    activate:
      on-profile: prod
  flyway:
    clean-disabled: true
  data:
    redis:
      url: ${REDIS_URL}
  session:
    timeout: 10m
    redis:
      namespace: operador-zero:oauth-session
      repository-type: default
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
server:
  shutdown: graceful
  servlet:
    session:
      cookie:
        name: OZ_OAUTH_SESSION
        http-only: true
        secure: true
        same-site: lax
app:
  auth:
    cookie:
      secure: true
      same-site: None
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
