import { AlertTriangle, CheckCircle2, ClipboardCheck, RefreshCw, ShieldCheck, Swords } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useState } from 'react'
import { contestPerformance, getMyPerformance, getOperations, getReviewablePerformance, getTeamWorkspace, Operation, PerformanceRecord, reviewPerformance, savePerformance, Team } from './api'

const statusLabels:Record<string,string>={PENDING:'Pendente',SELF_DECLARED:'Autodeclarado',ORGANIZER_CONFIRMED:'Confirmado pelo organizador',TEAM_CONFIRMED:'Confirmado pela equipe',CONTESTED:'Contestado',CORRECTED:'Corrigido',REJECTED:'Rejeitado'}
const resultLabels:Record<string,string>={WIN:'Vitória',LOSS:'Derrota',DRAW:'Empate',NONE:'Sem resultado'}

export function PerformancePage(){
 const [mine,setMine]=useState<PerformanceRecord[]>([]),[reviewable,setReviewable]=useState<PerformanceRecord[]>([]),[operations,setOperations]=useState<Operation[]>([]),[team,setTeam]=useState<Team|null>(null),[feedback,setFeedback]=useState(''),[pending,setPending]=useState('')
 const load=useCallback(async()=>{try{const [my,reviews,ops,workspace]=await Promise.all([getMyPerformance(),getReviewablePerformance(),getOperations(''),getTeamWorkspace()]);setMine(my.items);setReviewable(reviews.items.filter(item=>!item.currentUserRecord));setOperations(ops.items.filter(item=>item.status==='FINISHED'&&['CONFIRMED','CHECKED_IN'].includes(item.participantStatus||'')));setTeam(workspace.team);}catch{setFeedback('Não foi possível carregar os registros de desempenho.')}},[])
 useEffect(()=>{void load()},[load])
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),operationId=String(d.get('operationId')),existing=mine.find(item=>item.operationId===operationId);setPending('save');try{await savePerformance(operationId,{eliminations:Number(d.get('eliminations')),deaths:Number(d.get('deaths')),objectivesCompleted:Number(d.get('objectivesCompleted')),roundWins:Number(d.get('roundWins')),result:d.get('result'),positionUsed:d.get('positionUsed'),representedTeamId:d.get('representedTeamId')||null,notes:d.get('notes'),highlightReceived:d.get('highlightReceived'),abandoned:d.get('abandoned')==='on',participationScope:d.get('participationScope'),penaltyPoints:Number(d.get('penaltyPoints')||0),version:existing?.version||0});setFeedback('Desempenho registrado e enviado para confirmação.');e.currentTarget.reset();await load()}catch(err){setFeedback(err instanceof Error?err.message:'Não foi possível salvar o desempenho.')}finally{setPending('')}}
 const review=async(item:PerformanceRecord,action:string)=>{const correction=action==='CORRECT';let payload:Record<string,unknown>={action,version:item.version,notes:''};if(correction){const eliminations=window.prompt('Eliminações corrigidas',String(item.eliminations));if(eliminations===null)return;const deaths=window.prompt('Mortes corrigidas',String(item.deaths));if(deaths===null)return;const objectives=window.prompt('Objetivos corrigidos',String(item.objectivesCompleted));if(objectives===null)return;const penalties=window.prompt('Pontos de penalidade',String(item.penaltyPoints));if(penalties===null)return;payload={...payload,eliminations:Number(eliminations),deaths:Number(deaths),objectivesCompleted:Number(objectives),roundWins:item.roundWins,result:item.result,penaltyPoints:Number(penalties),notes:window.prompt('Observação da correção')||''}}else if(action==='REJECT'){const reason=window.prompt('Motivo da rejeição');if(!reason)return;payload.notes=reason}setPending(item.id);try{await reviewPerformance(item.id,payload);setFeedback('Revisão registrada.');await load()}catch(err){setFeedback(err instanceof Error?err.message:'Não foi possível revisar o registro.')}finally{setPending('')}}
 const contest=async(item:PerformanceRecord)=>{const reason=window.prompt('Explique o motivo da contestação (mínimo de 10 caracteres)');if(!reason)return;setPending(item.id);try{await contestPerformance(item.id,reason);setFeedback('Contestação enviada para análise.');await load()}catch(err){setFeedback(err instanceof Error?err.message:'Não foi possível contestar.')}finally{setPending('')}}
 return <main className="module-page"><header><p>HISTÓRICO CONFIÁVEL</p><h1>Registro de desempenho</h1><span>Registre seus números e acompanhe confirmações, correções ou contestações.</span></header>{feedback&&<p className="module-feedback" role="status">{feedback}</p>}
 <section className="module-section"><div className="module-section-title"><div><small>NOVO REGISTRO</small><h2>Desempenho após a operação</h2><p>Somente operações finalizadas com sua presença confirmada aparecem aqui.</p></div><Swords/></div>{operations.length===0?<div className="module-state"><p>Nenhuma operação está disponível para registro.</p></div>:<form className="module-form" onSubmit={submit}><div className="form-grid"><label><span>Operação</span><select name="operationId" required><option value="">Selecione</option>{operations.map(op=><option value={op.id} key={op.id}>{op.name} · {new Date(`${op.operationDate}T12:00:00`).toLocaleDateString('pt-BR')}</option>)}</select></label><label><span>Resultado</span><select name="result"><option value="NONE">Sem resultado</option><option value="WIN">Vitória</option><option value="LOSS">Derrota</option><option value="DRAW">Empate</option></select></label>{team&&<label><span>Equipe representada</span><select name="representedTeamId"><option value="">Nenhuma</option><option value={team.id}>{team.name} [{team.acronym}]</option></select></label>}<label><span>Eliminações</span><input type="number" name="eliminations" min={0} max={10000} defaultValue={0} required/></label><label><span>Mortes</span><input type="number" name="deaths" min={0} max={10000} defaultValue={0} required/></label><label><span>Objetivos cumpridos</span><input type="number" name="objectivesCompleted" min={0} max={1000} defaultValue={0} required/></label><label><span>Vitórias por rodada</span><input type="number" name="roundWins" min={0} max={1000} defaultValue={0} required/></label><label><span>Função utilizada</span><input name="positionUsed" maxLength={48}/></label><label><span>Participação</span><select name="participationScope"><option value="FULL">Completa</option><option value="PARTIAL">Parcial</option></select></label><label><span>Destaque recebido</span><input name="highlightReceived" maxLength={160}/></label><label><span>Pontos de penalidade</span><input type="number" name="penaltyPoints" min={0} step="0.01" defaultValue={0}/></label></div><label><span>Observações</span><textarea name="notes" maxLength={1000}/></label><label className="check-field"><input type="checkbox" name="abandoned"/> Houve abandono da operação</label><button className="module-primary" disabled={pending==='save'}><ClipboardCheck/> Registrar desempenho</button></form>}</section>
 <RecordSection title="Meus registros" items={mine} pending={pending} empty="Você ainda não registrou desempenho." onReview={review} onContest={contest}/>
 {reviewable.length>0&&<RecordSection title="Aguardando sua revisão" items={reviewable} pending={pending} empty="" onReview={review} onContest={contest}/>}</main>
}

function RecordSection({title,items,pending,empty,onReview,onContest}:{title:string;items:PerformanceRecord[];pending:string;empty:string;onReview:(item:PerformanceRecord,action:string)=>Promise<void>;onContest:(item:PerformanceRecord)=>Promise<void>}){return <section className="module-section"><div className="module-section-title"><div><small>DESEMPENHO</small><h2>{title}</h2></div><ShieldCheck/></div>{items.length===0?<div className="module-state"><p>{empty}</p></div>:<div className="performance-list">{items.map(item=><article key={item.id}><div className="performance-head"><div><small>{statusLabels[item.status]||item.status}</small><h3>{item.operatorCallsign} · {item.operationName}</h3><p>{new Date(`${item.operationDate}T12:00:00`).toLocaleDateString('pt-BR')} · {resultLabels[item.result]||item.result}</p></div><strong>{item.eliminations-item.deaths>=0?'+':''}{item.eliminations-item.deaths} saldo</strong></div><div className="performance-stats"><span><b>{item.eliminations}</b> eliminações</span><span><b>{item.deaths}</b> mortes</span><span><b>{item.objectivesCompleted}</b> objetivos</span><span><b>{Number(item.penaltyPoints).toFixed(2)}</b> penalidades</span></div>{item.organizerNotes&&<p className="performance-note">Observação: {item.organizerNotes}</p>}<div className="performance-actions">{item.canReviewAsOrganizer&&<><button disabled={pending===item.id} onClick={()=>void onReview(item,'CONFIRM_ORGANIZER')}><CheckCircle2/> Confirmar como organizador</button><button disabled={pending===item.id} onClick={()=>void onReview(item,'CORRECT')}><RefreshCw/> Corrigir</button><button disabled={pending===item.id} onClick={()=>void onReview(item,'REJECT')}><AlertTriangle/> Rejeitar</button></>}{item.canReviewAsTeam&&<button disabled={pending===item.id} onClick={()=>void onReview(item,'CONFIRM_TEAM')}><ShieldCheck/> Confirmar pela equipe</button>}{item.canContest&&<button disabled={pending===item.id} onClick={()=>void onContest(item)}><AlertTriangle/> Contestar</button>}</div></article>)}</div>}</section>}
