import { BarChart3, MapPin, Trophy } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { getOperatorRanking, RankingEntry } from './api'

export function RankingsPage(){
 const [items,setItems]=useState<RankingEntry[]>([]),[ruleVersion,setRuleVersion]=useState(''),[selected,setSelected]=useState<RankingEntry|null>(null),[error,setError]=useState('')
 const load=async(city='',stateCode='')=>{try{const result=await getOperatorRanking(city,stateCode);setItems(result.items);setRuleVersion(result.ruleVersion);setError('')}catch{setError('Não foi possível carregar o ranking.')}}
 useEffect(()=>{void load()},[])
 const filter=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);void load(String(d.get('city')),String(d.get('stateCode')))}
 return <main className="module-page"><header><p>DESEMPENHO CONFIRMADO</p><h1>Rankings</h1><span>Pontuação calculada com participação, eliminações, objetivos, resultados, confirmações e penalidades.</span></header>{error&&<p className="module-feedback module-feedback--error">{error}</p>}
 <section className="module-section"><div className="module-section-title"><div><small>FILTROS</small><h2>Ranking geral de operadores</h2></div><Trophy/></div><form className="module-form module-form--inline" onSubmit={filter}><label><span>Cidade</span><input name="city" maxLength={80}/></label><label><span>Estado</span><input name="stateCode" maxLength={2} pattern="[A-Za-z]{2}"/></label><button className="module-primary">Aplicar filtros</button></form></section>
 <section className="module-section"><div className="module-section-title"><div><small>{ruleVersion||'REGRA OFICIAL'}</small><h2>{items.length?`${items.length} operadores classificados`:'Ranking ainda sem resultados'}</h2></div><BarChart3/></div>{items.length===0?<div className="module-state"><p>Registros válidos aparecerão depois que operações finalizadas tiverem presença e desempenho registrados.</p></div>:<div className="ranking-table"><div className="ranking-row ranking-row--header"><span>Posição</span><span>Operador</span><span>Local</span><span>Operações</span><span>Pontos</span></div>{items.map(item=><button className="ranking-row" key={item.operatorId} onClick={()=>setSelected(item)}><strong>#{item.position}</strong><span><b>{item.callsign}</b><small>{item.teamAcronym?`[${item.teamAcronym}] · `:''}@{item.username}</small></span><span><MapPin/>{item.city&&item.stateCode?`${item.city}/${item.stateCode}`:'Não informado'}</span><span>{item.operationsConsidered}</span><strong>{Number(item.finalScore).toFixed(2)}</strong></button>)}</div>}</section>
 {selected&&<section className="ranking-detail" role="dialog" aria-modal="true" aria-label={`Detalhamento de ${selected.callsign}`}><button className="dialog-close" onClick={()=>setSelected(null)} aria-label="Fechar">×</button><small>POSIÇÃO #{selected.position}</small><h2>{selected.callsign}</h2><p>{selected.displayName} · @{selected.username}</p><dl><div><dt>Pontuação bruta</dt><dd>{Number(selected.gross).toFixed(2)}</dd></div><div><dt>Bônus</dt><dd>+{Number(selected.bonus).toFixed(2)}</dd></div><div><dt>Penalidades</dt><dd>−{Number(selected.penalties).toFixed(2)}</dd></div><div><dt>Fator aplicado</dt><dd>{Math.round(Number(selected.factor)*100)}%</dd></div><div><dt>Operações consideradas</dt><dd>{selected.operationsConsidered}</dd></div><div><dt>Pontuação final</dt><dd>{Number(selected.finalScore).toFixed(2)}</dd></div></dl></section>}
 </main>
}
